import type {
  ProjectModel,
  ProjectModelBlock,
  ProjectModelHandler,
  ProjectModelScreen,
} from "@/types/project";

/**
 * Deterministic Project Model → TypeScript generation. This is the "Model →
 * Code" direction of the Ideaven architecture: the blocks are the source,
 * the emitted program is a faithful, readable projection of them. Hand-edited
 * code and the reverse (code → blocks) direction arrive with the code-editor
 * milestone — until then this view is generated, never hand-writable, and
 * never lies about where the truth lives.
 */

/** One source-map entry: a generated line tied to the block that produced it. */
export interface SourceMapEntry {
  line: number;
  handlerId?: string;
  blockId?: string;
}

export interface GeneratedScreen {
  code: string;
  map: SourceMapEntry[];
}

/** Emit the runnable TypeScript for one screen's logic. */
export function screenToTypeScript(model: ProjectModel, screen: ProjectModelScreen): string {
  return screenToTypeScriptDetailed(model, screen).code;
}

/** Emit the TypeScript plus a block→line source map. */
export function screenToTypeScriptDetailed(
  model: ProjectModel,
  screen: ProjectModelScreen,
): GeneratedScreen {
  const lines: string[] = [];
  const map: SourceMapEntry[] = [];
  const handlers = screen.logic?.handlers ?? [];

  const push = (text: string, entry?: Omit<SourceMapEntry, "line">) => {
    lines.push(text);
    if (entry) map.push({ line: lines.length, ...entry });
  };

  push(`// Screen: ${screen.name} — generated by Ideaven from the Project Model.`);
  push(`// Source of truth: the block logic in the builder, not this file.`);
  push(`import type { ScreenApi } from "@ideaven/runtime";`);
  push(``);
  push(`export function register${sanitizeIdent(screen.name)}(api: ScreenApi) {`);

  if (handlers.length === 0) {
    push(`  // No event handlers yet — add blocks in the Blocks mode.`);
  }

  for (const handler of handlers) {
    const comment: string[] = [];
    comment.push(``);
    comment.push(`  // ${commentFor(model, screen, handler)}`);
    for (const text of comment) push(text);

    const callback = handler.body.length === 0 ? "() => {}" : "() => {";
    if (handler.componentId === null) {
      push(`  api.onScreen("${handler.event}", ${callback}`, { handlerId: handler.id });
    } else {
      push(
        `  api.onComponent("${handler.componentId}", "${handler.event}", ${callback}`,
        { handlerId: handler.id },
      );
    }
    for (const statement of handler.body) {
      emitStatement(push, model, statement, 2);
    }
    if (handler.body.length > 0) push(`  });`);
  }

  push(`}`);
  return { code: lines.join("\n"), map };
}

function emitStatement(
  push: (text: string, entry?: { handlerId?: string; blockId?: string }) => void,
  model: ProjectModel,
  block: ProjectModelBlock,
  depth: number,
) {
  const pad = "  ".repeat(depth);
  switch (block.type) {
    case "set-property": {
      const componentId = str(block.inputs?.componentId);
      const property = str(block.inputs?.property);
      push(
        `${pad}api.setProperty(${JSON.stringify(componentId)}, ${JSON.stringify(property)}, ${emitExpression(push, model, block.slots?.value)});`,
        { blockId: block.id },
      );
      return;
    }
    case "set-variable":
      push(
        `${pad}api.setVariable(${JSON.stringify(str(block.inputs?.name))}, ${emitExpression(push, model, block.slots?.value)});`,
        { blockId: block.id },
      );
      return;
    case "show-message":
      push(`${pad}api.show(${emitExpression(push, model, block.slots?.message)});`, {
        blockId: block.id,
      });
      return;
    case "navigate":
      push(`${pad}api.navigate(${JSON.stringify(str(block.inputs?.screenId))});`, {
        blockId: block.id,
      });
      return;
    case "if": {
      push(`${pad}if (${emitExpression(push, model, block.slots?.condition)}) {`, {
        blockId: block.id,
      });
      for (const child of block.children ?? []) emitStatement(push, model, child, depth + 1);
      if ((block.elseChildren ?? []).length > 0) {
        push(`${pad}} else {`, { blockId: block.id });
        for (const child of block.elseChildren ?? [])
          emitStatement(push, model, child, depth + 1);
      }
      push(`${pad}}`, { blockId: block.id });
      return;
    }
    default:
      push(`${pad}// unsupported block type "${block.type}" — skipped by the generator`);
  }
}

function emitExpression(
  push: (text: string, entry?: { handlerId?: string; blockId?: string }) => void,
  model: ProjectModel,
  block: ProjectModelBlock | undefined,
): string {
  if (!block) return `"" /* empty slot */`;
  switch (block.type) {
    case "text":
      return JSON.stringify(str(block.inputs?.value));
    case "number": {
      const value = block.inputs?.value;
      return typeof value === "number" ? String(value) : "0";
    }
    case "get-property":
      return `api.getProperty(${JSON.stringify(str(block.inputs?.componentId))}, ${JSON.stringify(str(block.inputs?.property))})`;
    case "get-variable":
      return `api.getVariable(${JSON.stringify(str(block.inputs?.name))})`;
    case "join":
      return `api.join(${emitExpression(push, model, block.slots?.a)}, ${emitExpression(push, model, block.slots?.b)})`;
    case "equals":
      return `api.equals(${emitExpression(push, model, block.slots?.a)}, ${emitExpression(push, model, block.slots?.b)})`;
    case "add":
      return `(Number(${emitExpression(push, model, block.slots?.a)}) + Number(${emitExpression(push, model, block.slots?.b)}))`;
    default:
      return `null /* unsupported expression "${block.type}" */`;
  }
}

function commentFor(model: ProjectModel, screen: ProjectModelScreen, handler: ProjectModelHandler): string {
  if (handler.componentId === null) return `when the screen ${handler.event}s`;
  const component = findComponent(screen.components, handler.componentId);
  if (!component) {
    return `when a deleted component ${handler.event}s (reconnect this handler in Blocks)`;
  }
  return `when ${describeComponent(component)} ${handler.event}s`;
}

// ---- helpers ----------------------------------------------------------------------

function str(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function findComponent(
  components: ProjectModelScreen["components"],
  id: string,
): { id: string; type: string; props?: Record<string, unknown> } | undefined {
  for (const component of components) {
    if (component.id === id) return component;
    const nested = component.children ? findComponent(component.children, id) : undefined;
    if (nested) return nested;
  }
  return undefined;
}

/** Human description used in generated comments (tree-safe). */
function describeComponent(component: { id: string; type: string; props?: Record<string, unknown> }): string {
  const text = component.props?.text ?? component.props?.label;
  const name = typeof text === "string" && text.trim() ? ` "${text.trim().slice(0, 24)}"` : "";
  return `${component.type}${name} (${component.id})`;
}

/** Turn a screen name into a valid exported identifier. */
function sanitizeIdent(name: string): string {
  const ident = name.replace(/[^a-zA-Z0-9]/g, "");
  return /^[0-9]/.test(ident) ? `Screen${ident}` : ident || "Screen";
}
