import type { ExtensionManifest, ExtensionMethodSpec } from "@/types/extension";

/**
 * Extension starter templates (Task 05). Every template generates a REAL
 * starter structure in the actual IDEAVEN extension schema: a validated
 * manifest (components/methods/events/blocks), generated documentation, and
 * a matching source skeleton — so "Create Extension" never opens an empty
 * technical environment.
 */

export interface GeneratedStarter {
  manifest: ExtensionManifest;
  docs: string;
  source: string;
}

export interface ExtensionTemplate {
  id: string;
  label: string;
  tagline: string;
  kind: "component" | "blocks" | "mixed";
  youWillLearn: string;
  generate(name: string, summary: string): GeneratedStarter;
}

const docsHeader = (name: string, summary: string, what: string): string =>
  `# ${name}\n\n${summary || what}\n\n## What this extension does\n\n${what}\n\n## How to install it\n\n1. Open **Extensions** in your dashboard.\n2. Find **${name}** under *Yours*.\n3. Run **Build AIX** in the Studio, then install it — its blocks appear in the builder's Blocks palette (\u2b21 section).\n`;

const propsSection = (props: Array<{ key: string; label: string; type: string; default?: unknown }>): string =>
  `## Properties\n\n| Property | Type | Default | Description |\n|---|---|---|---|\n${props
    .map((p) => `| ${p.key} | ${p.type} | ${JSON.stringify(p.default ?? "")} | ${p.label} |`)
    .join("\n")}\n`;

const methodsSection = (
  methods:
    | Array<{ id: string; label: string; params?: Array<{ key: string; type: string }> }>
    | undefined,
): string =>
  `## Methods\n\n${(methods ?? [])
    .map((m) => {
      const params = (m.params ?? []).map((p) => p.key).join(", ");
      return `- **${m.id}**(${params}) — ${m.label}`;
    })
    .join("\n")}\n`;

const eventsSection = (events: Array<{ id: string; label: string }> | undefined): string =>
  `## Events\n\n${(events ?? []).map((e) => `- **${e.id}** — ${e.label}`).join("\n")}\n`;

const blocksSection = (blocks: Array<{ type: string; kind: string; label: string }> | undefined): string =>
  `## Blocks\n\n${(blocks ?? [])
    .map((b) => `- \`${b.type}\` (${b.kind}) — ${b.label}`)
    .join("\n")}\n`;

const exampleSection = (example: string): string => `## Example\n\n\u0060\u0060\u0060json\n${example}\n\u0060\u0060\u0060\n`;

const tail = `\n---\n\nGenerated by Ideaven Extension Studio from this extension's real manifest — regenerate any time after editing it.\n`;

/** App Inventor-style Java skeleton generated from the same metadata. */
const javaSource = (
  pkg: string,
  className: string,
  spec: {
    props: Array<{ key: string; label: string; type: string }>;
    methods: Array<{ id: string; label: string; params?: Array<{ key: string; type: string }> }>;
    events: Array<{ id: string; label: string }> | undefined;
    visible: boolean;
  },
): string => {
  const base = spec.visible ? "AndroidViewContainer" : "AndroidNonvisibleComponent";
  const propGetters = spec.props
    .map((p) => {
      const javaType = p.type === "number" ? "int" : p.type === "boolean" ? "boolean" : "String";
      const safe = p.key.charAt(0).toUpperCase() + p.key.slice(1);
      const zero = p.type === "number" ? "0" : p.type === "boolean" ? "false" : '\"\"';
      return `  @SimpleProperty(description = "${p.label}")\n  public ${javaType} Get${safe}() {\n    return ${zero}; // TODO: read your stored value\n  }\n`;
    })
    .join("\n");
  const methodStubs = spec.methods
    .map((m) => {
      const params = (m.params ?? []).map((p) => `${p.type === "number" ? "int" : "String"} ${p.key}`).join(", ");
      return `  @SimpleFunction(description = "${m.label}")\n  public void ${m.id.charAt(0).toUpperCase() + m.id.slice(1)}(${params}) {\n    // TODO: implement ${m.label}\n  }\n`;
    })
    .join("\n");
  const eventDispatchers = (spec.events ?? [])
    .map((e) => {
      const safe = e.id.charAt(0).toUpperCase() + e.id.slice(1);
      return `  /** Call this from your implementation when ${e.label} happens. */\n  public void Raise${safe}() {\n    EventDispatcher.dispatchEvent(this, form, "${e.id}");\n  }\n`;
    })
    .join("\n");
  return `package ${pkg};\n\nimport com.google.appinventor.components.annotations.SimpleFunction;\nimport com.google.appinventor.components.annotations.SimpleProperty;\nimport com.google.appinventor.components.runtime.EventDispatcher;\nimport com.google.appinventor.components.runtime.${base};\nimport com.google.appinventor.components.runtime.ComponentContainer;\nimport com.google.appinventor.components.runtime.Form;\n\n/**\n * ${className} — generated starter by Ideaven Extension Studio.\n * Fill in the TODOs; the manifest already declares this surface.\n */\npublic class ${className} extends ${base} {\n\n  private Form form;\n\n  public ${className}(ComponentContainer container) {\n    super(container.$form());\n    this.form = container.$form();\n  }\n\n${propGetters}\n\n${methodStubs}\n\n${eventDispatchers}}\n`;
};

const slugify = (name: string): string =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "my-extension";

const pascal = (name: string): string => {
  const parts = name.replace(/[^a-zA-Z0-9 ]/g, " ").split(/\s+/).filter(Boolean);
  const joined = parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
  return /^[0-9]/.test(joined) ? "Ext" + joined : joined || "MyExtension";
};

// ---- 1. UI Component -----------------------------------------------------------

const uiTemplate: ExtensionTemplate = {
  id: "ui-component",
  label: "UI Component",
  tagline: "A visible component users drag onto a screen — a rating bar, a custom badge, anything styled.",
  kind: "component",
  youWillLearn: "declaring properties, a Click event, and a method",
  generate(name: string, summary: string): GeneratedStarter {
    const className = pascal(name);
    const props = [
      { key: "text", type: "text", label: "The text shown on the component" },
      { key: "color", type: "text", label: "The accent color" },
      { key: "fontSize", type: "number", label: "Text size in px" },
    ];
    const methods = [{ id: "reset", label: `Reset the ${name} to its starting state` }];
    const events = [{ id: "clicked", label: "When the user taps the component" }];
    const manifest: ExtensionManifest = {
      format: 1,
      name,
      components: [
        {
          id: className,
          label: `A ${name} element users can style and tap`,
          props: props.map((p) => ({ key: p.key, type: p.type === "number" ? "number" : p.type === "boolean" ? "boolean" : "text" })),
        },
      ],
      methods,
      events,
      blocks: [{ type: "reset", kind: "statement", category: "ui", label: `${name} reset` }],
      dependencies: [],
    };
    const docs =
      docsHeader(name, summary, `${name} is a visible UI component: users drag it onto a screen, style it with its properties, and react when it is tapped.`) +
      propsSection(props) +
      methodsSection(manifest.methods) +
      eventsSection(manifest.events) +
      blocksSection(manifest.blocks) +
      exampleSection(JSON.stringify({ component: className, props: { text: "Hello!", color: "#5743d9", fontSize: 16 } }, null, 2)) +
      tail;
    const source = javaSource(`com.ideaven.${slugify(name)}`, className, { props, methods, events, visible: true });
    return { manifest, docs, source };
  },
};

// ---- 2. Game Component (the TetrisBoard reference) ------------------------------

const gameTemplate: ExtensionTemplate = {
  id: "game-component",
  label: "Game Component",
  tagline: "A game board with properties, methods, and events — modeled on TetrisBoard.",
  kind: "component",
  youWillLearn: "properties, methods, and events working together",
  generate(name: string, summary: string): GeneratedStarter {
    const className = pascal(name) || "TetrisBoard";
    const props = [
      { key: "rows", type: "number", label: "Grid height in cells" },
      { key: "columns", type: "number", label: "Grid width in cells" },
      { key: "cellSize", type: "number", label: "Cell size in px" },
      { key: "theme", type: "text", label: "Visual theme name" },
    ];
    const methods: ExtensionMethodSpec[] = [
      { id: "startGame", label: "Start a new game" },
      { id: "pause", label: "Pause the running game" },
      { id: "reset", label: "Reset the board and score" },
      { id: "dropPiece", label: "Drop the current piece", params: [{ key: "column", type: "number" }] },
    ];
    const events = [
      { id: "piecePlaced", label: "A piece locked into the board" },
      { id: "lineCleared", label: "One or more lines were cleared" },
      { id: "scoreChanged", label: "The score changed" },
      { id: "gameOver", label: "No more moves — the game ended" },
    ];
    const manifest: ExtensionManifest = {
      format: 1,
      name,
      components: [
        {
          id: className,
          label: "A game board with a rows×columns grid, falling pieces, and scoring",
          props: props.map((p) => ({ key: p.key, type: "number" })),
        },
      ],
      methods,
      events,
      blocks: [
        { type: "startGame", kind: "statement", category: "control", label: `${name} start game` },
        { type: "pause", kind: "statement", category: "control", label: `${name} pause` },
        { type: "reset", kind: "statement", category: "control", label: `${name} reset` },
        { type: "dropPiece", kind: "statement", category: "control", label: `${name} drop piece in column {column}`, inputs: [{ key: "column", kind: "number" }] },
        { type: "score", kind: "expression", category: "variables", label: `${name} score` },
      ],
      dependencies: [],
    };
    const docs =
      docsHeader(name, summary, `${name} is a game board component: configure the grid with its properties, drive it with methods, and react to its events.`) +
      propsSection(props) +
      methodsSection(manifest.methods) +
      eventsSection(manifest.events) +
      blocksSection(manifest.blocks) +
      exampleSection(JSON.stringify({ component: className, props: { rows: 20, columns: 10, cellSize: 24, theme: "classic" }, calls: ["startGame()", "dropPiece(column: 3)"], react: ["when scoreChanged → update the score label"] }, null, 2)) +
      tail;
    const source = javaSource(`com.ideaven.${slugify(name)}`, className, { props, methods, events, visible: true });
    return { manifest, docs, source };
  },
};

// ---- 3. Utility ------------------------------------------------------------------

const utilityTemplate: ExtensionTemplate = {
  id: "utility",
  label: "Utility",
  tagline: "Pure logic blocks — no UI. Text tools, math helpers, formatting.",
  kind: "blocks",
  youWillLearn: "methods with parameters and expression blocks",
  generate(name: string, summary: string): GeneratedStarter {
    const methods: ExtensionMethodSpec[] = [
      { id: "reverseText", label: "Reverse a piece of text", params: [{ key: "text", type: "text" }] },
      { id: "countWords", label: "Count the words in a text", params: [{ key: "text", type: "text" }] },
    ];
    const manifest: ExtensionManifest = {
      format: 1,
      name,
      components: [],
      methods,
      events: [],
      blocks: [
        { type: "reverseText", kind: "expression", category: "text", label: `${name} reverse {text}`, inputs: [{ key: "text", kind: "text" }] },
        { type: "countWords", kind: "expression", category: "text", label: `${name} word count of {text}`, inputs: [{ key: "text", kind: "text" }] },
      ],
      dependencies: [],
    };
    const docs =
      docsHeader(name, summary, `${name} is a utility extension: pure logic users call from blocks — no UI, no state.`) +
      methodsSection(manifest.methods) +
      eventsSection(manifest.events) +
      blocksSection(manifest.blocks) +
      exampleSection(JSON.stringify({ blocks: ["reverseText(text: 'hello') returns 'olleh'", "countWords(text: 'hello world') returns 2"] }, null, 2)) +
      tail;
    const source = javaSource(`com.ideaven.${slugify(name)}`, pascal(name), { props: [], methods, events: manifest.events, visible: false });
    return { manifest, docs, source };
  },
};

// ---- 4. Data / API -----------------------------------------------------------------

const dataTemplate: ExtensionTemplate = {
  id: "data-api",
  label: "Data / API",
  tagline: "Fetch data from a web service and raise an event when it arrives.",
  kind: "mixed",
  youWillLearn: "methods, async events, and passing data along",
  generate(name: string, summary: string): GeneratedStarter {
    const methods: ExtensionMethodSpec[] = [
      { id: "fetchData", label: "Fetch JSON from a URL", params: [{ key: "url", type: "text" }] },
      { id: "setHeader", label: "Set a request header", params: [{ key: "name", type: "text" }, { key: "value", type: "text" }] },
    ];
    const events = [
      { id: "dataReceived", label: "The response arrived" },
      { id: "requestFailed", label: "The request failed" },
    ];
    const manifest: ExtensionManifest = {
      format: 1,
      name,
      components: [],
      methods,
      events,
      blocks: [
        { type: "fetchData", kind: "statement", category: "connectivity", label: `${name} fetch data from {url}`, inputs: [{ key: "url", kind: "text" }] },
        { type: "lastResponse", kind: "expression", category: "connectivity", label: `${name} last response` },
      ],
      dependencies: [],
    };
    const docs =
      docsHeader(name, summary, `${name} talks to a web service: call fetchData, wait for dataReceived, read the response. The preview shows the request shape; live network calls run in your exported app.`) +
      methodsSection(manifest.methods) +
      eventsSection(manifest.events) +
      blocksSection(manifest.blocks) +
      exampleSection(JSON.stringify({ calls: ["fetchData(url: 'https://api.example.com/weather')"], react: ["when dataReceived → parse and show"] }, null, 2)) +
      tail;
    const source = javaSource(`com.ideaven.${slugify(name)}`, pascal(name), { props: [], methods, events, visible: false });
    return { manifest, docs, source };
  },
};

// ---- 5. Device / Sensor -------------------------------------------------------------

const sensorTemplate: ExtensionTemplate = {
  id: "device-sensor",
  label: "Device / Sensor",
  tagline: "Tap into device signals — a pedometer-style event source.",
  kind: "component",
  youWillLearn: "event-driven design and honest capability states",
  generate(name: string, summary: string): GeneratedStarter {
    const methods: ExtensionMethodSpec[] = [
      { id: "startListening", label: "Start listening for signals" },
      { id: "stopListening", label: "Stop listening" },
    ];
    const events = [
      { id: "signalDetected", label: "A signal was detected" },
      { id: "availabilityChanged", label: "The sensor became available or unavailable" },
    ];
    const manifest: ExtensionManifest = {
      format: 1,
      name,
      components: [
        {
          id: pascal(name),
          label: "A non-visible sensor listener raising events on detection",
          props: [],
        },
      ],
      methods,
      events,
      blocks: [
        { type: "startListening", kind: "statement", category: "sensors", label: `${name} start listening` },
        { type: "stopListening", kind: "statement", category: "sensors", label: `${name} stop listening` },
      ],
      dependencies: [],
    };
    const docs =
      docsHeader(name, summary, `${name} listens to device signals and raises events. Sensors only fire on real hardware — the preview never simulates readings.`) +
      methodsSection(manifest.methods) +
      eventsSection(manifest.events) +
      blocksSection(manifest.blocks) +
      exampleSection(JSON.stringify({ react: ["when signalDetected → flash the screen"], note: "Sensors need a real device (or an emulator with sensor support)." }, null, 2)) +
      tail;
    const source = javaSource(`com.ideaven.${slugify(name)}`, pascal(name), { props: [], methods, events, visible: false });
    return { manifest, docs, source };
  },
};

// ---- 6. Custom Renderer ---------------------------------------------------------------

const rendererTemplate: ExtensionTemplate = {
  id: "custom-renderer",
  label: "Custom Renderer",
  tagline: "A component that draws itself — charts, gauges, custom shapes.",
  kind: "component",
  youWillLearn: "visible components with drawing methods",
  generate(name: string, summary: string): GeneratedStarter {
    const methods: ExtensionMethodSpec[] = [
      { id: "redraw", label: "Repaint with the current data", params: [{ key: "data", type: "text" }] },
      { id: "clear", label: "Clear the drawing" },
    ];
    const events = [{ id: "tapped", label: "The user tapped the drawing" }];
    const manifest: ExtensionManifest = {
      format: 1,
      name,
      components: [
        {
          id: pascal(name),
          label: "A component that paints its own visuals",
          props: [],
        },
      ],
      methods,
      events,
      blocks: [
        { type: "redraw", kind: "statement", category: "media", label: `${name} redraw with {data}`, inputs: [{ key: "data", kind: "text" }] },
        { type: "clear", kind: "statement", category: "media", label: `${name} clear` },
      ],
      dependencies: [],
    };
    const docs =
      docsHeader(name, summary, `${name} draws its own visuals. The Ideaven preview shows your declared shape; the drawing itself is your source code, running in your exported app.`) +
      methodsSection(manifest.methods) +
      eventsSection(manifest.events) +
      blocksSection(manifest.blocks) +
      exampleSection(JSON.stringify({ calls: ["redraw(data: '1,2,3,4')"] }, null, 2)) +
      tail;
    const source = javaSource(`com.ideaven.${slugify(name)}`, pascal(name), { props: [], methods, events, visible: true });
    return { manifest, docs, source };
  },
};

// ---- 7. Advanced Runtime ---------------------------------------------------------------

const advancedTemplate: ExtensionTemplate = {
  id: "advanced-runtime",
  label: "Advanced Runtime",
  tagline: "Start from the raw schema — full control, minimal guidance.",
  kind: "mixed",
  youWillLearn: "the whole schema, your way",
  generate(name: string, summary: string): GeneratedStarter {
    const manifest: ExtensionManifest = {
      format: 1,
      name,
      components: [],
      methods: [],
      events: [],
      blocks: [],
      dependencies: [],
    };
    const docs =
      docsHeader(name, summary, `${name} starts from the raw schema — declare components, methods, events, and blocks yourself in the Manifest tab.`) +
      `## Schema quick reference\n\n- \u0060components\u0060 — visible/non-visible components and their properties\n- \u0060methods\u0060 — callable functions\n- \u0060events\u0060 — signals the extension raises\n- \u0060blocks\u0060 — the palette entries users drag\n- \u0060dependencies\u0060 — informational; must exist in the registry at build time\n`;
    const source = javaSource(`com.ideaven.${slugify(name)}`, pascal(name), {
      props: [],
      methods: [{ id: "initialize", label: "Set up the extension" }],
      events: [],
      visible: false,
    });
    return { manifest, docs, source };
  },
};

export const EXTENSION_TEMPLATES: ExtensionTemplate[] = [
  uiTemplate,
  gameTemplate,
  utilityTemplate,
  dataTemplate,
  sensorTemplate,
  rendererTemplate,
  advancedTemplate,
];
